# Generated by Django 5.2.8 on 2025-11-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0002_lotegeneracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotegeneracion',
            name='frecuencia_mora',
            field=models.CharField(default='Por única vez', max_length=50),
        ),
        migrations.AddField(
            model_name='lotegeneracion',
            name='tipo_recargo',
            field=models.CharField(choices=[('fijo', 'Monto Fijo'), ('porcentaje', 'Porcentaje')], default='fijo', max_length=10),
        ),
        migrations.AddField(
            model_name='lotegeneracion',
            name='valor_mora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
