# Generated by Django 5.2.8 on 2025-11-20 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0003_lotegeneracion_frecuencia_mora_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrera',
            options={'ordering': ['nombre'], 'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='plandepago',
            options={'ordering': ['carrera', 'nombre'], 'verbose_name': 'Plan de Pago', 'verbose_name_plural': 'Planes de Pago'},
        ),
        migrations.AddField(
            model_name='carrera',
            name='modalidad',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual')], default='PRESENCIAL', max_length=20, verbose_name='Modalidad'),
        ),
        migrations.AddField(
            model_name='plandepago',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuotas.carrera', verbose_name='Carrera Asociada'),
        ),
        migrations.AddField(
            model_name='plandepago',
            name='monto_mensual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Mensual Base'),
        ),
        migrations.AddField(
            model_name='plandepago',
            name='porcentaje_mora',
            field=models.PositiveIntegerField(default=0, help_text='Ej: 10 para un 10%', verbose_name='Porcentaje de Mora (%)'),
        ),
        migrations.AlterField(
            model_name='lotegeneracion',
            name='carrera',
            field=models.ForeignKey(help_text='Generar cuotas para alumnos de esta carrera.', on_delete=django.db.models.deletion.PROTECT, to='cuotas.carrera'),
        ),
        migrations.AlterField(
            model_name='lotegeneracion',
            name='plan_pago',
            field=models.ForeignKey(help_text='Generar cuotas solo para alumnos con este plan.', on_delete=django.db.models.deletion.PROTECT, to='cuotas.plandepago'),
        ),
        migrations.AlterField(
            model_name='plandepago',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Plan'),
        ),
        migrations.AlterUniqueTogether(
            name='plandepago',
            unique_together={('nombre', 'carrera')},
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('legajo', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Legajo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='DNI')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('cohorte', models.IntegerField(verbose_name='Cohorte de Ingreso')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuotas.carrera', verbose_name='Carrera')),
                ('plan_de_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuotas.plandepago', verbose_name='Plan de Pago Asignado')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
