# Generated by Django 5.2.8 on 2025-11-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0004_alter_carrera_options_alter_plandepago_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrera',
            options={'ordering': ['nombre', 'modalidad'], 'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Carrera'),
        ),
        migrations.AlterUniqueTogether(
            name='carrera',
            unique_together={('nombre', 'modalidad')},
        ),
    ]
