# Generated by Django 5.2.8 on 2025-11-20 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0005_alter_carrera_options_alter_carrera_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plandepago',
            options={'ordering': ['-anio', 'carrera', 'nombre'], 'verbose_name': 'Plan de Pago', 'verbose_name_plural': 'Planes de Pago'},
        ),
        migrations.AlterUniqueTogether(
            name='plandepago',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='plandepago',
            name='anio',
            field=models.IntegerField(default=2023, verbose_name='Año del Plan'),
        ),
        migrations.AlterField(
            model_name='plandepago',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuotas.carrera', verbose_name='Carrera Asociada'),
        ),
        migrations.AlterUniqueTogether(
            name='plandepago',
            unique_together={('nombre', 'carrera', 'anio')},
        ),
    ]
