# Generated by Django 5.2.8 on 2025-11-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0006_alter_plandepago_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plandepago',
            name='porcentaje_mora',
        ),
        migrations.AddField(
            model_name='plandepago',
            name='cantidad_cuotas',
            field=models.IntegerField(default=10, verbose_name='Cantidad de Cuotas Anuales'),
        ),
        migrations.AddField(
            model_name='plandepago',
            name='mora',
            field=models.PositiveIntegerField(default=0, help_text='Porcentaje de recargo por mora. Ej: 10 para un 10%', verbose_name='Mora (%)'),
        ),
    ]
