# Generated by Django 5.2.8 on 2025-11-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0007_remove_plandepago_porcentaje_mora_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotegeneracion',
            old_name='año_generado',
            new_name='anio_generado',
        ),
        migrations.RemoveField(
            model_name='lotegeneracion',
            name='cohorte',
        ),
        migrations.AddField(
            model_name='lotegeneracion',
            name='alumnos',
            field=models.ManyToManyField(blank=True, related_name='lotes_generacion', to='cuotas.alumno'),
        ),
        migrations.AddField(
            model_name='lotegeneracion',
            name='fecha_programacion',
            field=models.DateTimeField(blank=True, help_text='Si se programa, esta es la fecha y hora de ejecución.', null=True),
        ),
        migrations.AddField(
            model_name='lotegeneracion',
            name='monto_total_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto mensual del plan por la cantidad de cuotas.', max_digits=12, null=True),
        ),
    ]
