# Generated by Django 5.2.8 on 2025-11-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0009_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotegeneracion',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el lote está activo o fue anulado.'),
        ),
    ]
