# Generated by Django 5.2.8 on 2025-11-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0010_lotegeneracion_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='monto_ajustado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nuevo monto si se aplica un ajuste manual.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cuota',
            name='motivo_ajuste',
            field=models.TextField(blank=True, help_text='Razón del ajuste manual.', null=True),
        ),
        migrations.AddField(
            model_name='cuota',
            name='vencimiento_ajustado',
            field=models.DateField(blank=True, help_text='Nueva fecha de vencimiento si se aplica un ajuste.', null=True),
        ),
    ]
